# Generated by Django 5.1.6 on 2025-02-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_farmer_email_alter_farmer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
